baseURL = 'http://slimemoldgrappling.com/'
languageCode = 'en-us'
theme = 'hugo-theme-relearn'

[params]
images = [ "images/hero.png" ]
description = "If it can learn, so can we."
themeVariant = "auto"
disableToc = true
disableBreadCrumb = true
editURL = "https://github.com/trydydd/selforganizedjj/edit/main/content/"
disableLandingPageButton = true
ordersectionsby = "weight"
alwaysopen = "false"
collapsibleMenu = true
disableSearchHiddenPages = false
disableSeoHiddenPages = true
contentDir = "content"